name: Mandala
favicon: null
layout_spectrum: 0.30087
typography_spectrum: 0.65377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0000'
    - '#ffffff'
    - '#251f20'
    - '#e38920'
    - '#feff00'
  brandStrength: 0.3490342446602881
  lightness: 0.9933348295744509
  saturation: 0.2512925330083817
  rhythmicContrast: 0.9481746978126466
purpose: []
