name: Mandala
favicon: null
layout_spectrum: 0.39782948954962194
typography_spectrum: 0.6331383255310357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3490342446602881
  lightness: 0.9933348295744509
  saturation: 0.2512925330083817
  rhythmicContrast: 0.9481746978126466
purpose: []
